export const PEOPLE_FETCH_ATTEMPT = 'PEOPLE_FETCH_ATTEMPT';
export const PEOPLE_FETCH_SUCCESS = 'PEOPLE_FETCH_SUCCESS';
export const PEOPLE_FETCH_FAILURE = 'PEOPLE_FETCH_FAILURE';

export const PERSON_UPDATE_ATTEMPT = 'PERSON_UPDATE_ATTEMPT';
export const PERSON_UPDATE_SUCCESS = 'PERSON_UPDATE_SUCCESS';
export const PERSON_UPDATE_FAILURE = 'PERSON_UPDATE_FAILURE';

export const PERSON_DELETE_ATTEMPT = 'PERSON_DELETE_ATTEMPT';
export const PERSON_DELETE_SUCCESS = 'PERSON_DELETE_SUCCESS';
export const PERSON_DELETE_FAILURE = 'PERSON_DELETE_FAILURE';

export const PERSON_CREATE_ATTEMPT = 'PERSON_CREATE_ATTEMPT';
export const PERSON_CREATE_SUCCESS = 'PERSON_CREATE_SUCCESS';
export const PERSON_CREATE_FAILURE = 'PERSON_CREATE_FAILURE';
